import Foundation

/// A fixture skills library shaped like the one an iOS team accumulates over a year: eight
/// capability families, most with siblings, two superseded entries nobody deleted, one that
/// points at a successor that was never written, and a spread of last-touched dates.
/// Every skill here is a stand-in for a real SKILL.md; the fixture is the *index*, not the prose.
public enum Fixture {
    public static let now = Date(timeIntervalSince1970: 1_788_998_400) // 2026-09-07

    static func day(_ daysAgo: Int) -> Date { now.addingTimeInterval(-Double(daysAgo) * 86_400) }

    public static let catalog = SkillCatalog([
        // test ------------------------------------------------------------------------
        Skill(id: "test-xctest", family: "test",
              title: "Write XCTest unit tests",
              summary: "Add XCTestCase classes with XCTAssert checks for a module and run them from the scheme.",
              keywords: ["xctest", "unit", "test", "xctassert", "xctestcase", "assert"],
              updatedAt: day(210)),
        Skill(id: "test-swift-testing", family: "test",
              title: "Write Swift Testing unit tests",
              summary: "Add @Test functions and @Suite types using #expect and #require, with tags for filtering.",
              keywords: ["swift", "testing", "unit", "test", "expect", "require", "suite", "tags"],
              updatedAt: day(12),
              preconditions: [.minimumToolVersion(tool: "swift", version: 6)]),
        Skill(id: "test-xcuitest", family: "test",
              title: "Write XCUITest UI tests",
              summary: "Drive the app on a simulator with XCUIApplication and accessibility identifiers.",
              keywords: ["xcuitest", "ui", "test", "simulator", "accessibility", "identifier", "xcuiapplication"],
              updatedAt: day(95),
              preconditions: [.fileExists("App.xcodeproj")]),
        Skill(id: "test-snapshot", family: "test",
              title: "Add snapshot tests",
              summary: "Record and compare reference images for views using a snapshot testing library.",
              keywords: ["snapshot", "test", "reference", "image", "view", "record"],
              updatedAt: day(140),
              preconditions: [.fileExists("Package.resolved")]),

        // release ---------------------------------------------------------------------
        Skill(id: "release-testflight-v1", family: "release",
              title: "Upload a build to TestFlight (altool)",
              summary: "Archive, export an ipa and upload to TestFlight with xcrun altool and an app-specific password.",
              keywords: ["testflight", "upload", "ipa", "archive", "altool", "build", "beta", "export"],
              version: 1, updatedAt: day(420),
              supersededBy: "release-testflight-v2"),
        Skill(id: "release-testflight-v2", family: "release",
              title: "Upload a build to TestFlight (App Store Connect API)",
              summary: "Archive, export with ExportOptions.plist and upload to TestFlight using an App Store Connect API key.",
              keywords: ["testflight", "upload", "ipa", "archive", "build", "beta", "api", "key"],
              version: 2, updatedAt: day(30),
              preconditions: [.fileExists("ExportOptions.plist")]),
        Skill(id: "release-app-store-submit", family: "release",
              title: "Submit for App Store review",
              summary: "Fill review notes, screenshots and metadata, then submit the build for App Store review.",
              keywords: ["app", "store", "review", "submit", "metadata", "screenshots", "release"],
              updatedAt: day(60)),
        Skill(id: "release-version-bump", family: "release",
              title: "Bump marketing version and build number",
              summary: "Increment MARKETING_VERSION and CURRENT_PROJECT_VERSION consistently across targets.",
              keywords: ["version", "bump", "build", "number", "marketing", "agvtool"],
              updatedAt: day(75)),

        // build -----------------------------------------------------------------------
        Skill(id: "build-spm-package", family: "build",
              title: "Build and test a Swift package",
              summary: "Run swift build and swift test for a Package.swift-based library, with a scratch path.",
              keywords: ["swift", "build", "package", "spm", "test", "scratch", "path"],
              updatedAt: day(20),
              preconditions: [.fileExists("Package.swift")]),
        Skill(id: "build-xcodeproj", family: "build",
              title: "Build an Xcode project from the command line",
              summary: "Run xcodebuild against a scheme and destination for an .xcodeproj or .xcworkspace.",
              keywords: ["xcodebuild", "build", "scheme", "destination", "project", "workspace"],
              updatedAt: day(45),
              preconditions: [.fileExists("App.xcodeproj")]),
        Skill(id: "build-xcode-cloud", family: "build",
              title: "Configure an Xcode Cloud workflow",
              summary: "Set up ci_scripts post-clone steps and a workflow for pull request builds on Xcode Cloud.",
              keywords: ["xcode", "cloud", "workflow", "ci", "build", "ci_scripts", "pull", "request"],
              updatedAt: day(160),
              preconditions: [.fileExists("ci_scripts")]),
        Skill(id: "build-fastlane", family: "build",
              title: "Run a fastlane lane",
              summary: "Execute and extend lanes in the Fastfile for build, test and beta distribution.",
              keywords: ["fastlane", "lane", "fastfile", "build", "ci", "beta"],
              updatedAt: day(300),
              preconditions: [.fileExists("Fastfile")]),

        // ui --------------------------------------------------------------------------
        Skill(id: "ui-swiftui-view", family: "ui",
              title: "Build a SwiftUI view",
              summary: "Compose a SwiftUI view with @State and @Observable models and preview it.",
              keywords: ["swiftui", "view", "state", "observable", "preview", "body", "screen"],
              updatedAt: day(15)),
        Skill(id: "ui-uikit-viewcontroller", family: "ui",
              title: "Build a UIKit view controller",
              summary: "Create a UIViewController programmatically with Auto Layout constraints and no storyboard.",
              keywords: ["uikit", "viewcontroller", "uiviewcontroller", "autolayout", "constraints", "screen", "programmatic"],
              version: 2, updatedAt: day(50)),
        Skill(id: "ui-uikit-storyboard", family: "ui",
              title: "Build a UIKit screen in a storyboard",
              summary: "Lay out a UIViewController in Interface Builder with segues and outlets.",
              keywords: ["uikit", "viewcontroller", "storyboard", "segue", "outlet", "interface", "builder", "screen"],
              version: 1, updatedAt: day(600),
              supersededBy: "ui-uikit-viewcontroller"),
        Skill(id: "ui-liquid-glass", family: "ui",
              title: "Adopt Liquid Glass",
              summary: "Apply glassEffect and GlassEffectContainer to custom chrome on iOS 26 and later.",
              keywords: ["liquid", "glass", "glasseffect", "container", "ios26", "chrome", "material", "view"],
              updatedAt: day(8),
              preconditions: [.minimumToolVersion(tool: "ios", version: 26)]),

        // concurrency -----------------------------------------------------------------
        Skill(id: "concurrency-swift6-strict", family: "concurrency",
              title: "Fix strict concurrency errors",
              summary: "Resolve Sendable and actor isolation diagnostics under Swift 6 language mode.",
              keywords: ["concurrency", "sendable", "actor", "isolation", "swift6", "strict", "async", "background"],
              updatedAt: day(25),
              preconditions: [.minimumToolVersion(tool: "swift", version: 6)]),
        Skill(id: "concurrency-gcd", family: "concurrency",
              title: "Move work off the main thread with GCD",
              summary: "Use DispatchQueue and DispatchGroup to run work in the background and hop back to main.",
              keywords: ["concurrency", "dispatchqueue", "gcd", "background", "main", "thread", "async", "queue"],
              updatedAt: day(380)),
        Skill(id: "concurrency-combine-migration", family: "concurrency",
              title: "Migrate Combine pipelines to async/await",
              summary: "Replace publishers and sinks with AsyncSequence and structured tasks.",
              keywords: ["combine", "publisher", "async", "await", "asyncsequence", "migration", "sink"],
              updatedAt: day(110)),

        // persistence -----------------------------------------------------------------
        Skill(id: "persist-swiftdata", family: "persistence",
              title: "Persist models with SwiftData",
              summary: "Define @Model types, configure a ModelContainer and query with @Query.",
              keywords: ["swiftdata", "model", "modelcontainer", "query", "persist", "store", "save", "database"],
              updatedAt: day(40),
              preconditions: [.minimumToolVersion(tool: "ios", version: 17)]),
        Skill(id: "persist-coredata", family: "persistence",
              title: "Persist models with Core Data",
              summary: "Design an xcdatamodeld, subclass NSManagedObject and save through a viewContext.",
              keywords: ["coredata", "nsmanagedobject", "xcdatamodeld", "persist", "store", "save", "database", "context"],
              updatedAt: day(250)),
        Skill(id: "persist-keychain", family: "persistence",
              title: "Store secrets in the Keychain",
              summary: "Save and read tokens with SecItem APIs and the right accessibility class.",
              keywords: ["keychain", "secitem", "token", "secret", "secure", "store", "save"],
              updatedAt: day(90)),

        // ai --------------------------------------------------------------------------
        Skill(id: "ai-foundation-models", family: "ai",
              title: "Call the on-device Foundation Models framework",
              summary: "Create a LanguageModelSession, use @Generable output and stream responses on device.",
              keywords: ["foundation", "models", "languagemodelsession", "generable", "on-device", "llm", "prompt", "stream"],
              updatedAt: day(10),
              preconditions: [.minimumToolVersion(tool: "ios", version: 26)]),
        Skill(id: "ai-claude-messages", family: "ai",
              title: "Call the Claude Messages API",
              summary: "Send a messages request with tools and stream the response from the API.",
              keywords: ["claude", "messages", "api", "tools", "llm", "prompt", "stream", "anthropic"],
              updatedAt: day(18)),
        Skill(id: "ai-prompt-cache", family: "ai",
              title: "Keep the prompt cache warm",
              summary: "Order system prompt, tools and history so the request prefix stays stable across turns.",
              keywords: ["prompt", "cache", "prefix", "system", "tools", "llm", "cost", "ttl"],
              updatedAt: day(3)),

        // debug -----------------------------------------------------------------------
        Skill(id: "debug-crash-symbolicate", family: "debug",
              title: "Symbolicate a crash log",
              summary: "Match a crash report to its dSYM and read the symbolicated stack.",
              keywords: ["crash", "symbolicate", "dsym", "stack", "log", "report"],
              updatedAt: day(70)),
        Skill(id: "debug-memory-leak", family: "debug",
              title: "Find a memory leak",
              summary: "Use Instruments Leaks and the memory graph to locate retain cycles.",
              keywords: ["memory", "leak", "instruments", "retain", "cycle", "weak", "graph"],
              updatedAt: day(130)),
        Skill(id: "debug-hang", family: "debug",
              title: "Diagnose a main-thread hang",
              summary: "Use Time Profiler and hang detection to find blocking work on the main thread.",
              keywords: ["hang", "main", "thread", "time", "profiler", "instruments", "blocking"],
              updatedAt: day(55)),
        Skill(id: "debug-oslog-v1", family: "debug",
              title: "Add os_log logging",
              summary: "Instrument code with os_log categories for Console filtering.",
              keywords: ["log", "oslog", "console", "logging", "category"],
              version: 1, updatedAt: day(500),
              supersededBy: "debug-logger-v2"),
    ])

    // Environments the benchmark cases resolve in.
    static let spmSwift6 = Environment(files: ["Package.swift", "Package.resolved"], toolVersions: ["swift": 6, "ios": 26])
    static let spmSwift5 = Environment(files: ["Package.swift", "Package.resolved"], toolVersions: ["swift": 5, "ios": 17])
    static let appProjectIOS26 = Environment(files: ["App.xcodeproj", "ExportOptions.plist"], toolVersions: ["swift": 6, "ios": 26])
    static let appProjectIOS17 = Environment(files: ["App.xcodeproj", "ExportOptions.plist"], toolVersions: ["swift": 6, "ios": 17])
    static let legacyApp = Environment(files: ["App.xcodeproj", "Fastfile"], toolVersions: ["swift": 5, "ios": 16])
    static let cloudApp = Environment(files: ["App.xcodeproj", "ci_scripts"], toolVersions: ["swift": 6, "ios": 26])

    /// Thirty-two cases. Each pairs a plausible agent query with the environment it was issued in.
    /// Several are deliberately generic ("upload the build") because that is what agents actually
    /// ask; the environment, not the wording, is what disambiguates the siblings.
    public static let benchmark: [BenchmarkCase] = [
        BenchmarkCase(id: "c01", query: "write unit tests for the parser with expect and a suite", environment: spmSwift6, expectedSkillID: "test-swift-testing"),
        BenchmarkCase(id: "c02", query: "write unit tests for the parser", environment: spmSwift5, expectedSkillID: "test-xctest"),
        BenchmarkCase(id: "c03", query: "add unit tests for the date formatter", environment: spmSwift6, expectedSkillID: "test-swift-testing"),
        BenchmarkCase(id: "c04", query: "add a ui test that taps through onboarding on the simulator", environment: appProjectIOS26, expectedSkillID: "test-xcuitest"),
        BenchmarkCase(id: "c05", query: "record snapshot tests for the settings view", environment: spmSwift6, expectedSkillID: "test-snapshot"),
        BenchmarkCase(id: "c06", query: "upload the build to testflight", environment: appProjectIOS26, expectedSkillID: "release-testflight-v2"),
        BenchmarkCase(id: "c07", query: "archive and export an ipa for beta testers", environment: appProjectIOS17, expectedSkillID: "release-testflight-v2"),
        BenchmarkCase(id: "c08", query: "submit the build for app store review with screenshots", environment: appProjectIOS26, expectedSkillID: "release-app-store-submit"),
        BenchmarkCase(id: "c09", query: "bump the marketing version and build number", environment: appProjectIOS26, expectedSkillID: "release-version-bump"),
        BenchmarkCase(id: "c10", query: "build and run the tests", environment: spmSwift6, expectedSkillID: "build-spm-package"),
        BenchmarkCase(id: "c11", query: "build the app for the ci run", environment: appProjectIOS26, expectedSkillID: "build-xcodeproj"),
        BenchmarkCase(id: "c12", query: "set up a pull request build workflow", environment: cloudApp, expectedSkillID: "build-xcode-cloud"),
        BenchmarkCase(id: "c13", query: "run the beta lane", environment: legacyApp, expectedSkillID: "build-fastlane"),
        BenchmarkCase(id: "c14", query: "build the package", environment: spmSwift6, expectedSkillID: "build-spm-package"),
        BenchmarkCase(id: "c15", query: "create a settings screen", environment: appProjectIOS26, expectedSkillID: "ui-swiftui-view"),
        BenchmarkCase(id: "c16", query: "create a uikit screen for the account page", environment: appProjectIOS17, expectedSkillID: "ui-uikit-viewcontroller"),
        BenchmarkCase(id: "c17", query: "add a uikit viewcontroller screen with constraints", environment: legacyApp, expectedSkillID: "ui-uikit-viewcontroller"),
        BenchmarkCase(id: "c18", query: "apply glass material to the custom tab bar chrome", environment: appProjectIOS26, expectedSkillID: "ui-liquid-glass"),
        BenchmarkCase(id: "c19", query: "apply glass material to the custom tab bar chrome", environment: appProjectIOS17, expectedSkillID: "ui-swiftui-view"),
        BenchmarkCase(id: "c20", query: "move the image decode off the main thread in the background", environment: spmSwift6, expectedSkillID: "concurrency-swift6-strict"),
        BenchmarkCase(id: "c21", query: "move the image decode off the main thread in the background", environment: legacyApp, expectedSkillID: "concurrency-gcd"),
        BenchmarkCase(id: "c22", query: "fix the sendable and actor isolation errors", environment: spmSwift6, expectedSkillID: "concurrency-swift6-strict"),
        BenchmarkCase(id: "c23", query: "replace the combine publisher pipeline with async await", environment: spmSwift6, expectedSkillID: "concurrency-combine-migration"),
        BenchmarkCase(id: "c24", query: "save the user's drafts to a local database", environment: appProjectIOS26, expectedSkillID: "persist-swiftdata"),
        BenchmarkCase(id: "c25", query: "save the user's drafts to a local database", environment: legacyApp, expectedSkillID: "persist-coredata"),
        BenchmarkCase(id: "c26", query: "store the auth token securely", environment: appProjectIOS26, expectedSkillID: "persist-keychain"),
        BenchmarkCase(id: "c27", query: "stream an llm response to a prompt on device", environment: appProjectIOS26, expectedSkillID: "ai-foundation-models"),
        BenchmarkCase(id: "c28", query: "stream an llm response to a prompt on device", environment: appProjectIOS17, expectedSkillID: "ai-claude-messages"),
        BenchmarkCase(id: "c29", query: "keep the system prompt and tools stable so the prefix caches", environment: spmSwift6, expectedSkillID: "ai-prompt-cache"),
        BenchmarkCase(id: "c30", query: "symbolicate this crash report with the dsym", environment: appProjectIOS26, expectedSkillID: "debug-crash-symbolicate"),
        BenchmarkCase(id: "c31", query: "find the retain cycle leaking the view model", environment: appProjectIOS26, expectedSkillID: "debug-memory-leak"),
        BenchmarkCase(id: "c32", query: "the feed freezes and blocks the main thread while scrolling", environment: appProjectIOS26, expectedSkillID: "debug-hang"),
    ]
}
